// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXLl5aSuUqS0dIHLbdh2mZ3p5kO783y88',
    appId: '1:339258866020:web:3b5c42ceb8f15268ad6271',
    messagingSenderId: '339258866020',
    projectId: 'recipe-app-3481a',
    authDomain: 'recipe-app-3481a.firebaseapp.com',
    storageBucket: 'recipe-app-3481a.firebasestorage.app',
    measurementId: 'G-695GKDKWVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC9FUVF1-TuBbLLtxdmLw9mQ930CI5rIg',
    appId: '1:339258866020:android:1649604dbf22d276ad6271',
    messagingSenderId: '339258866020',
    projectId: 'recipe-app-3481a',
    storageBucket: 'recipe-app-3481a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXLl5aSuUqS0dIHLbdh2mZ3p5kO783y88',
    appId: '1:339258866020:web:f7de14a499da856cad6271',
    messagingSenderId: '339258866020',
    projectId: 'recipe-app-3481a',
    authDomain: 'recipe-app-3481a.firebaseapp.com',
    storageBucket: 'recipe-app-3481a.firebasestorage.app',
    measurementId: 'G-L50QMVHT26',
  );
}
